#!/data/data/com.termux/files/usr/bin/env bash
# =============================================================================
#  setup-termux.sh - install the OmniRoute gateway + web-cookie bridges on
#  Android (Termux). One-shot installer; safe to re-run.
#
#  What this does:
#    1. Installs Termux packages: nodejs (24 LTS), git, binutils, and python
#       (only when GEMINI=1). LEAN by default (~1.5GB): the gateway + the
#       mimo-web bridge + the extension cover every chat route. Chromium
#       (~1GB, Google Flow images) and the gemini bridge build (~1.5GB of
#       rust/clang) are OPT-IN - see FLOW/GEMINI below.
#    2. npm installs the omniroute gateway globally.
#    3. Writes ~/.omniroute/.env with a fresh STORAGE_ENCRYPTION_KEY and the
#       ZAI_CAPTCHA_WORKER path (so zai captcha solving works on-device).
#    4. Installs the bridges: mimo-web (pure Node, always), gemini/gflow
#       (GEMINI=1, python + gemini_webapi), flowui (FLOW=1, playwright +
#       system chromium).
#    5. Installs the Cookie Pusher extension source to ~/omniroute-cookie-pusher
#       (load it in Kiwi Browser -> chrome://extensions -> Load unpacked).
#    6. Creates the start + Termux:Boot autostart scripts, then purges caches.
#
#  Options (env vars):
#    FULL=1    everything: chromium + gemini bridge (~5-6GB total).
#    FLOW=1    add Chromium (~1GB incl. deps) + the Google Flow image bridge.
#    GEMINI=1  add the gemini bridge build (rust/clang, ~1.5GB while building).
#
#  Usage:  bash setup-termux.sh
#  Then:   bash ~/omniroute-android/start-omniroute.sh   (or reboot the phone)
#  URL:    http://127.0.0.1:20128  (dashboard) / http://<phone-ip>:20128 from
#          other devices on the same Wi-Fi (gateway binds 0.0.0.0 by default).
# =============================================================================
set -euo pipefail

FLOW="${FLOW:-0}"
GEMINI="${GEMINI:-0}"
if [ "${FULL:-0}" = "1" ]; then FLOW=1; GEMINI=1; fi

echo "==> [1/8] Updating Termux packages..."
pkg update -y
pkg upgrade -y

echo "==> [2/8] Installing runtimes..."
# python is only needed for the gemini bridge (GEMINI=1) - the lean profile
# skips it (~100MB saved).
PKGS="nodejs-lts git binutils"
[ "$GEMINI" = "1" ] && PKGS="$PKGS python"
pkg install -y $PKGS
# Chromium for the flowui bridge (playwright uses the system browser).
# OPT-IN (FLOW=1): chromium comes from x11-repo + tur-repo and adds ~1GB
# incl. deps. The lean default skips it - chat routes work without it.
if [ "$FLOW" = "1" ] && ! command -v chromium >/dev/null 2>&1; then
  # chromium needs x11-repo (gtk3/libxkbcommon deps) AND tur-repo, then a
  # package refresh so both indexes are loaded before installing.
  pkg install -y x11-repo tur-repo 2>/dev/null || true
  pkg update 2>/dev/null || true
  pkg install -y chromium 2>/dev/null || echo "  (chromium install failed - flowui images disabled; set FLOW_BRIDGE_ENABLED=0)"
else
  echo "  (chromium skipped - FLOW=0; re-run with FLOW=1 to enable Google Flow images)"
fi

echo "==> [3/8] Installing omniroute gateway (npm global)..."
npm install -g --no-audit --no-fund omniroute@latest

echo "==> [4/8] Writing ~/.omniroute/.env ..."
mkdir -p ~/.omniroute
if [ ! -f ~/.omniroute/.env ]; then
  # fresh encryption key (only generated once; keep it safe)
  KEY=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
  cat > ~/.omniroute/.env <<EOF
# generated by setup-termux.sh on $(date -Iseconds)
PORT=20128
HOST=0.0.0.0
STORAGE_ENCRYPTION_KEY=$KEY
ZAI_CAPTCHA_WORKER=$HOME/.omniroute/zai-captcha-worker.js
EOF
  echo "  .env written (encryption key generated)"
else
  echo "  .env already exists - keeping it"
fi

echo "==> [5/8] Installing bridges..."
mkdir -p ~/omniroute-android ~/.omniroute/bridge

# --- mimo-web bridge (pure Node, no native deps) ---
if [ -d ~/omniroute-android/bridge/mimo-web-bridge ]; then
  ( cd ~/omniroute-android/bridge/mimo-web-bridge && npm install --omit=dev 2>/dev/null || true )
fi

# --- gemini/gflow bridge (python) - only when GEMINI=1 ---
if [ "$GEMINI" = "1" ] && [ -d ~/omniroute-android/bridge/gemini-bridge ]; then
  ( cd ~/omniroute-android/bridge/gemini-bridge && pip install --no-cache-dir -r requirements.txt 2>/dev/null || pip install --no-cache-dir gemini_webapi )
else
  echo "  (gemini bridge skipped - GEMINI=0; re-run with GEMINI=1 to enable)"
fi

# --- flowui bridge (playwright + system chromium) - only when FLOW=1 ---
# PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1: the bridge drives the system chromium
# via CHROME_PATH, so the ~200MB bundled browser download is pure waste.
if [ "$FLOW" = "1" ] && [ -d ~/omniroute-android/bridge/flow-browser ]; then
  ( cd ~/omniroute-android/bridge/flow-browser && PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 npm install --omit=dev --no-audit --no-fund 2>/dev/null || true )
else
  echo "  (flowui bridge skipped - FLOW=0; re-run with FLOW=1 to enable)"
fi

echo "==> [6/8] Copying the Cookie Pusher extension..."
# The extension source (this kit) - copy it so Kiwi can load it unpacked.
if [ -d ~/omniroute-android/extension ]; then
  cp -r ~/omniroute-android/extension ~/omniroute-cookie-pusher
  echo "  extension copied to ~/omniroute-cookie-pusher"
  echo "  -> Kiwi Browser: chrome://extensions -> Developer mode -> Load unpacked -> select that folder"
else
  echo "  WARN: extension/ not found next to this script - grab it from the kit"
fi

echo "==> [7/8] Installing Termux:Boot autostart..."
mkdir -p ~/.termux/boot
cp ~/omniroute-android/boot.sh ~/.termux/boot/omniroute-boot.sh 2>/dev/null || \
  echo "  WARN: boot.sh not found - skipping autostart"
chmod +x ~/.termux/boot/omniroute-boot.sh 2>/dev/null || true
# Termux:Boot needs battery optimization off for Termux + Termux:Boot in
# Android settings; run the app once after install to arm it.

echo "==> [8/8] Storage cleanup (purging npm/pip/pkg caches)..."
npm cache clean --force >/dev/null 2>&1 || true
rm -rf ~/.npm/_cacache 2>/dev/null || true
pip cache purge >/dev/null 2>&1 || true
pkg clean -y >/dev/null 2>&1 || true

echo "==> Done."
echo
echo "Start the stack now:    bash ~/omniroute-android/start-omniroute.sh"
echo "Dashboard:              http://127.0.0.1:20128"
echo "LAN (same Wi-Fi):       http://$(hostname -I 2>/dev/null | awk '{print $1}'):20128"
echo "Push sessions:          sign in on Kiwi -> Cookie Pusher -> Grab & push"
echo "Storage:                ~1.5-2GB (lean default); FULL=1 adds ~4GB"
echo
